</div>
<!-- /.container -->


        <div class="endRow">

        </div>
        <!-- Footer -->
        <footer>
            <div class="container">
                <div class="row">

                    <div class="col-xs-6 col-md-4">

                        <ul class='list-inline'>
                            <li>
                                <a href="https://twitter.com/theverynats">
                                    <i class="fa fa-twitter"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.facebook.com/theverynats">
                                    <i class="fa fa-facebook"></i>
                                </a>
                            </li>
                            <li>
                                <a href="https://www.instagram.com/theverynats">
                                    <i class="fa fa-instagram"></i>
                                </a>
                            </li>
                        </ul>
                    </div>

                    <div class="col-xs-6 col-md-8">
                        <p class="text-right">Copyright &copy; Natacha Cahorel 2016</p>
                    </div>

                </div>
                <!-- /.row -->
            </div>
        </footer>


    <!-- jQuery -->
    <script src="view/js/jquery.js"></script>
    
    <?php if($page=="ajouterArticle"): ?>
        <script src="view/js/jquery-ui.min.js"></script>
        <script src="view/js/app.js"></script>
    <?php endif; ?>
    <?php if($page=="article"): ?>
        <script src="view/js/article.js"></script>
    <?php endif; ?>
    <?php if($page=="inscription"): ?>
        <script src="view/js/inscription.js"></script>
    <?php endif; ?>


    <!-- Bootstrap Core JavaScript -->
    <script src="view/js/bootstrap.min.js"></script>

</body>

</html>
