<?php include "partials/header.phtml"; ?>


    <div class="banner">
        <!--
        <h1 class="page-header">
            Theverynats
        </h1>
        <h2>Food - Clothing - DIY</h2>
        -->
    </div>

    <!-- Title -->
      <div class="row topRow">

        <div class="col-md-7 blogFlux">

            <article>
                <div class="row">

                    <div class="col-md-12">
                        <h2>
                            Article Categories
                        </h2>
                        <p class="author">
                            <a href="#">All Cat</a>
                        </p>


                        <div class="row text-center">
                            <?php foreach ($categorie as $key => $value): ?>

                                <div class="col-md-12 col-sm-12">
                                    <div class="thumbnail2">
                                        <a href="index.php?page=unecategorie&idcat=<?= $value["id"] ?>">
                                            <img src="view/images/<?=($value["image"]);?>" alt="">
                                            <div class="caption">
                                                <h3><?= ($value["titre"]); ?></h3>
                                            </div>
                                            <p><?= $value["description"] ?></p>
                                        </a>
                                    </div>
                                </div>

                            <?php endforeach; ?>
                        </div>

                    </div>
                </div>

            </article>

        </div><!--/.col-xs-12.col-sm-9-->

        <!--sidebar-->
        <?php include "partials/nav.phtml"; ?>

      </div><!--/row-->


      <!-- Footer -->
      <?php include "partials/footer.phtml"; ?>