<?php include "partials/header.phtml"; ?>
  
  <div class="row"></div>

  <div class="col-md-4">
  </div>

  <div class="col-md-4">
    <div id="displayError">
    <?php if (!empty($errors)) : ?>
      <p class="alert alert-danger">
      <?php foreach ($errors as $key => $value) : ?>
          <?= $value; ?><br>
      <?php endforeach; ?>
      </p>
    <?php endif; ?>
    </div>
      <form class="form-signin" method="POST" novalidate id="inscriptionForm">
        <h2 class="form-signin-heading text-center">Create new admin account</h2>
        <label for="inputName" class="sr-only">Name</label>
        <input type="text" id="inputName" class="form-control" placeholder="Name" required autofocus name="name">
        <label for="inputfirstname" class="sr-only">Firstname</label>
        <input type="text" id="inputfirstname" class="form-control" placeholder="Firstname" required autofocus name="firstname">
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name="email">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="remember" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Create</button>
      </form>

  </div>

  <div class="col-md-4">
  </div
    </div> <!-- /container -->

  <div class="col-md-12 endLoginPage"></div>

<?php include "partials/footer.phtml"; ?>