<?php include "partials/header.phtml"; ?>
  
  <div class="col-md-4">
  </div>

  <div class="col-md-4">
      <form class="form-signin" method="POST" novalidate>
        <h2 class="form-signin-heading text-center">Access reserved</h2>
        <label for="inputEmail" class="sr-only">Email address</label>
        <input type="email" id="inputEmail" class="form-control" placeholder="Email address" required autofocus name="email">
        <label for="inputPassword" class="sr-only">Password</label>
        <input type="password" id="inputPassword" class="form-control" placeholder="Password" required name="password">
        <div class="checkbox">
          <label>
            <input type="checkbox" name="remember" value="remember-me"> Remember me
          </label>
        </div>
        <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
      </form>

  </div>

  <div class="col-md-4">
  </div>




    </div> <!-- /container -->

  <div class="col-md- 12 endLoginPage"></div>

<?php include "partials/footer.phtml"; ?>